name: CICD pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  tests:
    name: run test on PR
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: set up dockerfile
        uses: docker/setup-buildx-action@v3
      
      # - name: build and run tests
      - name: build docker image
        run: docker build -f Dockerfile.dev -t myapp .
      
      - name: run test
        run: docker run --rm -e CI=true myapp npm run test  --watchAll=false
  
  deploy:
    name: Deploy to amazon elastic beans
    if: github.event_name == 'push'  && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      
